version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./output:/app/output

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
