version: '3.8'

services:
  api:
    image: 060795916912.dkr.ecr.us-east-1.amazonaws.com/churn-prediction:latest
    build:
      context: ./api
    ports:
      - "8000:80"
    expose:
      - "80"
    volumes:
      - ./output:/app/output

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
